# Generated by Django 5.2.5 on 2026-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_publisher_ebook_author_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publisher',
            field=models.ManyToManyField(null=True, to='blog.publisher'),
        ),
    ]
