# Generated by Django 5.2.5 on 2026-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.TextField(),
        ),
    ]
